fail_fast: true
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terrascan
        args:
          - --args=--non-recursive
          # We set this to high as it suggests KMS keys for SNS Topics which would set a base cost of $1 per bundle...
          - --args=--severity=high
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-aws-credentials
      - id: no-commit-to-branch
        args: [-b, main]
