 # workaround from https://github.com/opensearch-project/helm-charts/issues/87
 extraInitContainers:
   - name: sysctl
     image: docker.io/bitnami/bitnami-shell:10-debian-10-r199
     imagePullPolicy: "IfNotPresent"
     command:
       - /bin/bash
       - -ec
       - |
         CURRENT=`sysctl -n vm.max_map_count`;
         DESIRED="262144";
         if [ "$DESIRED" -gt "$CURRENT" ]; then
             sysctl -w vm.max_map_count=262144;
         fi;
         CURRENT=`sysctl -n fs.file-max`;
         DESIRED="65536";
         if [ "$DESIRED" -gt "$CURRENT" ]; then
             sysctl -w fs.file-max=65536;
         fi;
     securityContext:
       runAsUser: 0
       # this is no-bueno, but seems the only way to get this to work in GKE...
       # https://github.com/opensearch-project/helm-charts/issues/87#issuecomment-982185661
       privileged: true
