version: '3.3'
services:
  nginx_80:
    image: nginx:latest
    container_name: nginx_80
    ports:
      - 80:80
    volumes:
      - /etc/composer/nginx.conf:/etc/nginx/nginx.conf
      - /etc/composer/index001.html:/etc/nginx/html/index.html
  nginx_8080:
    image: nginx:latest
    container_name: nginx_8080
    ports:
      - 8080:80
    volumes:
      - /etc/composer/nginx.conf:/etc/nginx/nginx.conf
      - /etc/composer/index002.html:/etc/nginx/html/index.html
